version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MAKE_API_TOKEN=${MAKE_API_TOKEN}
      - MAKE_API_BASE_URL=${MAKE_API_BASE_URL}
      - DATABASE_URL=${DATABASE_URL}
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5000:5000"
    depends_on:
      - backend
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
