version: "3.8"

services:
  fastapi-app:
    build: ./backend
    container_name: fastapi_chatbot
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY} 
    restart: always
